name: Step 1, Create a Discussion

# This step triggers when a user creates a new discussion.
# This workflow updates from step 1 to step 2.

on:
  discussion:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_discussion_created:
    name: On Discussion Created
    needs: get_current_step
    if: >-
      ${{
        !github.event.repository.is_template &&
        needs.get_current_step.outputs.current_step == 1 &&
        (github.event.discussion.category.name == 'Q&A' || github.event.discussion.category.name == 'Ideas')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare a branch and pull request
        run: |
          echo "Make sure we are on step 1"
          if [ "$(cat .github/steps/-step.txt)" != 1 ]
          then
            echo "Current step is not 1"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=step-2-reply
          git checkout -b $BRANCH

          echo "Update README to unlock Step 2"
          sed -i.bak 's/<!--STEP 1-->/<!--STEP 2-->/' README/1-create-a-discussion.md

          echo "Make a commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README/1-create-a-discussion.md
          git commit --message="✅ Step 1 complete: Created a discussion!"

          echo "Push"
          git push --set-upstream origin $BRANCH

          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to step 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: step-2-reply
