name: Step 3, Mark as Answered

# This step triggers when a user marks a comment as the answer in a discussion.
# This workflow updates from step 3 to step 4.

on:
  discussion:
    types: [answered]

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_answered:
    name: On Mark as Answered
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template &&
          needs.get_current_step.outputs.current_step == 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Prepare a branch and pull request
        run: |
          echo "Make sure we are on step 3"
          if [ "$(cat .github/steps/-step.txt)" != 3 ]
          then
            echo "Current step is not 3"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=step-4-organize
          git checkout -b $BRANCH

          echo "Update README to unlock Step 4"
          sed -i.bak 's/<!--STEP 3-->/<!--STEP 4-->/' README/3-mark-as-answered.md

          echo "Make a commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README/3-mark-as-answered.md
          git commit --message="✅ Step 3 complete: Marked a discussion as answered!"

          echo "Push"
          git push --set-upstream origin $BRANCH

          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to step 4
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
          branch_name: step-4-organize
