name: Step 4, Organize with Categories

# This step triggers when a discussion is edited (e.g., category changed).
# This workflow updates from step 4 to the finish step.

on:
  discussion:
    types: [edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_category_edit:
    name: On Discussion Category Change
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template &&
          needs.get_current_step.outputs.current_step == 4 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Prepare a branch and pull request
        run: |
          echo "Make sure we are on step 4"
          if [ "$(cat .github/steps/-step.txt)" != 4 ]
          then
            echo "Current step is not 4"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=finish-skill
          git checkout -b $BRANCH

          echo "Update README to unlock Finish"
          sed -i.bak 's/<!--STEP 4-->/<!--FINISHED-->/' README/4-organize-with-categories.md

          echo "Make a commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README/4-organize-with-categories.md
          git commit --message="✅ Step 4 complete: Organized discussion with categories!"

          echo "Push"
          git push --set-upstream origin $BRANCH

          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to finish step
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 4
          to_step: 5
          branch_name: finish-skill
