name: Finish, Congratulations

# This step triggers when the learner reaches the final step.
# No further steps needed—just a celebration!

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  celebrate:
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 You've completed the skill!
        run: echo "Congratulations on finishing the GitHub Discussions Skill!"
